### ISSUE TITLE
Please add support for Tengai Makyou Zero translation memory map

### ISSUE THREAD

**Issue by victordg-github** [SourMesen/Mesen-S#101]
All 3 games using SPC7110 works nicely now, thanks a lot for that! Yet there is a translation for Tengai Makyou Zero and it would be great if Mesen-S would also support the wonderful work done by Tom and his crew: https://www.romhacking.net/translations/3243/. I believe all major emulators (Snes, Bsnes, Higan...) added support for the extended memory required by the translation back when it as released.

**Comment by SourMesen** [comment]
Thanks for the request.
The translation should be working properly as of 8798a73deb2f46f37203657d1a9c606790240fa5 (unless you enable the option for "strict board mappings")

**Comment by victordg-github** [comment]
Thanks! I didn't have the chance to say thanks on the open ticket :) It's
running perfectly now, awesome work! :)
