### ISSUE TITLE
[Libretro] Disable "Gamename Loaded" Message

### ISSUE THREAD

**Issue by Awakened0** [SourMesen/Mesen-S#105]
Just a minor thing, but no other core (even Mesen) seem to have a message like this at every game bootup:
![Mega Man X (USA) (Rev 1)-200325-224200](https://user-images.githubusercontent.com/4565863/77605107-76a2ba00-6eea-11ea-87c3-0e8a65a7a8be.png)
I tend to like a clean bootup without messages like that.

**Comment by SourMesen** [comment]
Didn't even know this was a thing - I don't see it on my end, either (but that might be because of some option I don't have enabled or something, I tried looking for one, but couldn't find anything)

Either way, it *should* be gone now, let me know if it isn't.

**Comment by Awakened0** [comment]
If you have Onscreen Notifications and Graphics Widgets on under Settings, Onscreen Display, Onscreen Notifications it should have popped up. Anyways, it's gone now. Thanks!
