### ISSUE TITLE
Error when random loading game

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#107]
Hi dear Sour, thanks for fixing the loading random game option
I got this new error , when loading a random game
![image](https://user-images.githubusercontent.com/37517008/78170377-c2a1b180-744a-11ea-9c68-c62b48a55f2a.png)

it's true that the path's name to the folder is long.

Mesen-S build: 
![image](https://user-images.githubusercontent.com/37517008/78170472-e95fe800-744a-11ea-9d68-3f8721a1e5b8.png)

**Comment by SourMesen** [comment]
This is a Windows limitation.  Generally speaking, having paths longer than ~240 characters in Windows will break a lot of stuff (not just Mesen).  The simple fix is to change your directory structure.
