### ISSUE TITLE
[Not an Issue] Pacman Build script for Mesen-S for Arch Linux

### ISSUE THREAD

**Issue by furtabs** [SourMesen/Mesen-S#109]
If anyone wants to use this ill drop it here

https://hastebin.com/kilicemefu.bash

**Comment by furtabs** [comment]
AUR Page is up https://aur.archlinux.org/packages/mesen-s-git/

**Comment by SourMesen** [comment]
Thanks!  I added a link to the Arch Linux package in the readme.
