### ISSUE TITLE
Real problem with using full height of screen

### ISSUE THREAD

**Issue by mistepien** [SourMesen/Mesen-S#111]
Mesen-s does not use full height of screen. Bsnes can do that without any problem. In case of mesen-s there are bars above and below. It is also a result of incorrect screen ratio.

**Comment by SourMesen** [comment]
You can use the overscan options in Video settings -> Overscan to hide the top and bottom portions of the screen to hide the black bars.

**Comment by mistepien** [comment]
how it can be done in retroarch?

**Comment by mistepien** [comment]
I got it. Vertical Overscan x8 does a job.
