### ISSUE TITLE
Super Mario - Yossy Island Korean Patcher rom bug

### ISSUE THREAD

**Issue by Potmarigold** [SourMesen/Mesen-S#113]
1. Super Mario - Yossy Island Korean Patcher rom is not
    When I reset, the game is not saved

2. Main manu save cursor bug
    The game main screen cursor also has a different position

**Comment by SourMesen** [comment]
As far as I can tell, bsnes has the exact same issues, so this looks like it's a bug with the translation patch more than anything else.
