### ISSUE TITLE
Program crashes with error upon start-up

### ISSUE THREAD

**Issue by appollo147** [SourMesen/Mesen-S#114]
I get the message "Critical error (unabletostartmissingdependncies" whenever I try to load Messen-s.
Any help with this would be greatly appreciated.

**Comment by SourMesen** [comment]
What OS are you running?  Is it a 32-bits version of Windows?  If so, this is probably normal.

**Comment by SourMesen** [comment]
Would need more information to be able to help - closing this for now.
