### ISSUE TITLE
Analog sticks not working

### ISSUE THREAD

**Issue by NiBBa256** [SourMesen/Mesen-S#116]
Basically the title. I went to bind the SNES D-pad controls to the left analog stick of my Xbox 360 compatible controller but it keeps binding back to the controller's D-Pad. 
*Edit*: OK, I got it working now, but it took me several attempts to accomplish it.

**Comment by SourMesen** [comment]
So just to be sure, the problem seems to have been that the configuration was not getting saved properly?

Something similar has been reported in the past (on a new installation, afaik), but I've never been able to reproduce the bug locally.  I'll give it another shot when I have a chance.

**Comment by ghost** [comment]
@NiBBa256 ok close this issue then if its fixed
