### ISSUE TITLE
F-ZERO: Mode-7 Tilemap Viewer bugs?

### ISSUE THREAD

**Issue by egrandizio** [SourMesen/Mesen-S#117]
I was looking at the Tilemap Viewer in F-ZERO and I noticed that, although the graphics displayed seem to be accurate, the "Tile Number" data in the Tile Information box did not seem to be right. I did some testing, and it appears that all the accurate Tile Numbers are spaced out by 2, (meaning to find the right tile number for an x,y coordinate, you'd have to double the coordinate to find the right Tile Number) with the in-between tiles giving seemingly random other Tile Numbers.

This only seemed to be an issue for the track backgrounds using Mode-7, as the other backgrounds such as the menu seemed to have accurate Tile Numbers. (although I didn't test the menus in-depth, and I couldn't test other games)

**Comment by SourMesen** [comment]
Thanks for the report.

The calculations for mode 7 were wrong - it should be fixed now.  Also added a "tile address" field to make it easier to find the corresponding tile in the tile viewer.  I do eventually want to allow double-clicking, or something akin, to open up the tile viewer on the matching tile, too.
