### ISSUE TITLE
Lua API: Potentially missing command

### ISSUE THREAD

**Issue by egrandizio** [SourMesen/Mesen-S#118]
![image](https://user-images.githubusercontent.com/65352263/81948546-db67c000-95cf-11ea-9540-f6490594e9e4.png)

One of the commands for the Lua API to get the controller input pops up as a suggestion if you type it, but if I try to use it, it gives an error message. It looks like the help message is the one for the NES Mesen instead.

This is especially interesting because the function is in the Mesen-S LuaApi.cpp file,
![image](https://user-images.githubusercontent.com/65352263/81949025-5b8e2580-95d0-11ea-8ac7-b42c90615931.png)

. . . but it is not listed in the library section, where all the other commands are.
![image](https://user-images.githubusercontent.com/65352263/81949133-7f516b80-95d0-11ea-9e6a-011b117dbd37.png)

I'm not sure if this was an oversight or it just wasn't done being implemented yet, but I figured I'd bring it up.

**Comment by SourMesen** [comment]
Thanks for the report!

Looks like this was meant to be available, but was just not in the list of APIs.
I added it and fixed the description in the UI, too, so it should be working properly now.
