### ISSUE TITLE
Mesen-S-DevWin-0.1.0.36 crash

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen-S#12]
I get this error when checking for updates 
![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM5-11-2019-1 17 45 AM](https://user-images.githubusercontent.com/21169038/57565880-26cb0b00-738b-11e9-82f8-57f1706c748a.jpg)

**Comment by SourMesen** [comment]
Thanks for the report!  This is fixed by 28a02a464d2f3e6f840503032d946efe31efc9b4
