### ISSUE TITLE
[Libretro] SRAM autosave interval is not working 

### ISSUE THREAD

**Issue by klepp0906** [SourMesen/Mesen-S#121]
Ooof.  Just got turned onto this core and switched all my assets over to it.   Great core, love it.  Checks all my boxes.  Unfortunately i ran into this monster of a doozy that is imperative enough that if it cant be rectified ill have to swap again :(

Here is the issue i posted on the RA tracker https://github.com/libretro/RetroArch/issues/10644

Hoping something can be done about it but i'd be the last person with any idea of what it entails.

Thanks of course either way!

**Comment by klepp0906** [comment]
I presume the fact it does not work in mesen-s, means it does not work in mesen.  Both of which i am now using.

this is based off of someone on the retroarch discord 

> autosave interval only works for cores that use libretro facilities to save many (most) cores just flush data directly

**Comment by SourMesen** [comment]
Thanks for the report!

As far as I know, this should be working fine on the Mesen core, and it's probably just an oversight in the Mesen-S one, I'll take a look.

**Comment by klepp0906** [comment]
thats exceptional,  I appreciate it very much.

Im just trying to avoid a situation where i HAVE to shutdown properly to get a save written
whether that be through the autosave, or through the immediate flush is less important of course

mesen-s seems to require a proper shutdown or bust for a save to be written
which can present issue when closing with other frontends n such.  nevermind legimate crashes or power outages

**Comment by SourMesen** [comment]
Turns out it was basically just a typo in the code that was causing this to break (and I imagine it might have had some effect on achievements, too)

Should be fixed in the next build the buildbot compiles.  Let me know if you still have issues with it!

**Comment by klepp0906** [comment]
LOL i was JUST going to come make an issue report about crazy achievement happenings :)

huge thanks.  I appreciate it very much!
