### ISSUE TITLE
FF6 menu in PAL mode. 

### ISSUE THREAD

**Issue by NiBBa256** [SourMesen/Mesen-S#126]
![ff3usa_001](https://user-images.githubusercontent.com/47758660/82738697-ff4aa480-9d39-11ea-8c6f-d18ac4523b88.png)
The item list is missing and the HDMA gradient as well. If I switch to PAL while already in the item, skill or equip menu everything looks just fine. Also, this issue wasn't present while I was in caves. Is this supposed to happen on a real PAL SNES or is this a bug?

**Comment by SourMesen** [comment]
There is no version of FF6 that is meant to be run on PAL systems.  As far as I can tell, this is probably normal, a quick search seems to find similar videos on youtube.  There also exists this patch to get FF6 to run correctly with PAL timings, as far as I can tell: http://www.romhacking.net/hacks/106/

Generally speaking, though, you should just keep the region set to "auto" - a lot of games are likely to break (e.g like this), if you're playing them with the wrong region setting.
