### ISSUE TITLE
A question about gb/c disassembler

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#132]
Hi dear Sour,

I am amazed and surprised by the fact that you did add GB and GBC support (I am drooling :heart_eyes:).

The question is isn't it Z80 ?

**Comment by SourMesen** [comment]
I'm not sure what you mean?
The GB CPU is similar to a Z80, but different, several instructions are different, see: https://gbdev.gg8.se/wiki/articles/CPU_Comparision_with_Z80

**Comment by ghost** [comment]
Thank you so much for the info , I really was confused at first.
