### ISSUE TITLE
SNES Mouse in Mario Paint

### ISSUE THREAD

**Issue by carmiker** [SourMesen/Mesen-S#135]
I cannot seem to get the mouse working in Mario Paint. However, I am able to use it in other games, for example, T2 - The Arcade Game. I have tried using libretro, standalone, and my own unreleased build. Am I missing something obvious?

**Comment by SourMesen** [comment]
Mario Paint needs the mouse in player 1's port - is that where you're connecting it?  Seems to work fine on my end, at least.

**Comment by carmiker** [comment]
That was the obvious thing I was missing! Thank you.
