### ISSUE TITLE
Bilinear interpolation looks wrong in 0.4.0

### ISSUE THREAD

**Issue by rareblueape** [SourMesen/Mesen-S#138]
hi. ever since the update to 0.4.0, ive noticed the interpolation looks messy and off, and i'm not entirely sure why this is.
left: 0.3.0
right: 0.4.0
![ISSUE](https://user-images.githubusercontent.com/17790865/83973666-a1779a00-a8ad-11ea-8362-8870804f5b9d.png)

**Comment by SourMesen** [comment]
Thanks for the report.

This is the expected result as of this change: 5315ef44453f70b9b5a13aa1a3b40378bb102baf
More information is in this issue (and the articles linked there): #52 

Basically, the change makes it so the interpolated result uses colors that are closer to the original picture.  This makes it so the outline around the text does not get "bolder" when interpolation is turned on, etc.
