### ISSUE TITLE
Accurate PAL/NTSC aspect ratio issues

### ISSUE THREAD

**Issue by NiBBa256** [SourMesen/Mesen-S#139]
There is no option to get a proper automatic PAL/NTSC aspect ratio seen on a real SNES. As you know, the SNES has horizontally stretched pixels and , If I am not mistaken, on real hardware the 256x224 is stretched to a 320:224 picture. On PAL systems that would be 384:224 or 16:10 if 256x240 is used due to letterboxing. This option would be very convenient as it would make the picture look more like on real hardware.

**Comment by SourMesen** [comment]
This is possible via Options -> Video -> Aspect Ratio -> "Auto (NTSC or PAL based on game)"
This will switch between a 8:7 PAR (pixel aspect ratio, e.g the pixel is not square) for NTSC or 11:8 PAR for PAL.  As far as I know, this is generally the accepted pixel aspect ratios for NTSC and PAL on the SNES.

e.g, using the "240p suite" test rom, you can verify that a circle has its proper shape using 8:7 PAR:
![image](https://user-images.githubusercontent.com/21093973/84609115-990df900-ae83-11ea-97bd-50cf47085cd7.png)
