### ISSUE TITLE
Black bars on top and bottom of screen

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen-S#14]
![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM6-30-2019-12 06 38 PM](https://user-images.githubusercontent.com/21169038/60399801-02d8aa00-9b30-11e9-9197-99a8aa96a059.jpg)

DevWin-0.1.0.52

Here's my settings file if you need it.

[settings.zip](https://github.com/SourMesen/Mesen-S/files/3343147/settings.zip)

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Pentium G3240 @ 3.10GHz
	Haswell 22nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 698MHz (10-10-10-25)
Motherboard
	Gigabyte Technology Co. Ltd. H81-D3 (SOCKET 0)
Graphics
	ELEFW328 (1360x768@60Hz)
	Intel HD Graphics (Gigabyte)
	1023MB NVIDIA GeForce GT 720 (EVGA)
	ForceWare version: 417.35
	SLI Disabled
Storage
	931GB TOSHIBA DT01ACA100 (SATA )
Optical Drives
	HL-DT-ST DVDRAM GH24NSC0
Audio
	Realtek High Definition Audio

**Comment by SourMesen** [comment]
This is normal - games can either display 239 lines or 224 lines (the game selects the display mode).  The emulator always outputs 239 lines (and centers the 224-line picture in the middle of it).  You can use the overscan settings to remove the top/bottom 7/8 pixels to get rid of the black bars.

**Comment by Cibomatto2002** [comment]
Overscan does not work for me like it does in Mesen Here is a video I made to help you see what it looks like on my end.

https://www.youtube.com/watch?v=NUukYJ0m7LA&feature=youtu.be

I downloaded Mesen-SDevWin-0.1.0.3 and still the same problem.

**Comment by Cibomatto2002** [comment]
I was playing around with the Scale  and if I set it to 3:41 it will fill the screen but when I go out of full screen it forgets my settings and the black bars returns. 
![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM7-7-2019-11 52 18 PM](https://user-images.githubusercontent.com/21169038/60784002-c0583400-a112-11e9-9044-f58bff29f76d.jpg)

**Comment by SourMesen** [comment]
I've taken another look and it seems to be behaving as I would expect.
If you want to remove the black bars completely, you will need to either add overscan on left+right sides of the screen (e.g setting top to 7, and the rest to 8 seems to work nicely for 16:9) or use a custom aspect different from 16:9 to stretch the pixels a bit more vertically.

The "scale" setting gets kind of reset on restart because it's set based on the window's size when the program opens.

**Comment by Cibomatto2002** [comment]
Thanks that fixed it.
