### ISSUE TITLE
Exiting while maximized seems incorrect

### ISSUE THREAD

**Issue by NovaSquirrel** [SourMesen/Mesen-S#16]
I'm using build 0.1.0.77. On at least my computer, exiting Mesen-S while it's maximized seems to produce behavior where the rendered video stays maximized on the next launch, but the window itself uses the previous non-maximized size, resulting in a zooming and cropping effect.

![image](https://user-images.githubusercontent.com/1865623/61178303-8676aa00-a5b8-11e9-9229-07af88ca1a5a.png)

**Comment by SourMesen** [comment]
This should be fixed by c96e37145f399256227644d76a91d613348ee1ab - let me know if you still get issues with it (or if this broke something else size/scale-related)
