### ISSUE TITLE
erroneous tooltip label in Event Viewer

### ISSUE THREAD

**Issue by forarslys** [SourMesen/Mesen-S#18]
I have my 65816 code reading from an aboluste address around $4400 with the data bank register being $7E, and EventViewer recognizes that read as one from Register.

I assume this problem is attributed to CpuDebugger::ProcessRead only accepting a uint16_t address rather than a uint32_t and discarding the bank information?
The same problem happens to Write as well.

**Comment by SourMesen** [comment]
I actually noticed this myself last night, but was in the middle of other stuff so hadn't pushed a fix yet.
The CpuDebugger stuff dates from a few days ago when I added SA1 support, so not impossible that something else might be broken, too.

I committed a fix which should solve the problem - let me know if you find anything else!
