### ISSUE TITLE
Doom Slow down.

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen-S#19]
Using DevWin-0.2.0.8 I get slow downs on these to screens the game runs fine. 
![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM7-30-2019-11 30 13 PM](https://user-images.githubusercontent.com/21169038/62184381-71717900-b323-11e9-90e6-a01570ad7081.jpg)
![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM7-30-2019-11 32 14 PM](https://user-images.githubusercontent.com/21169038/62184382-720a0f80-b323-11e9-90b1-d9b753830a44.jpg)

Found another game where there is slowdown Kirby Super Star This only happens on this screen when playing the game it stays at 60 FPS.

![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM7-31-2019-12 12 28 AM](https://user-images.githubusercontent.com/21169038/62185534-7684f700-b328-11e9-92ed-ff84b4f3c796.jpg)

**Comment by SourMesen** [comment]
In this case, this is probably just your CPU not being able to keep up with the emulation.  I'll try to see if there's anything particular about these scenes that cause a higher CPU usage.

**Comment by Cibomatto2002** [comment]
Just wanted to share that on BSNES Version 108 both games run fine. Is Mesen-S more accurate on these games than BSNES? 
![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM7-31-2019-10 37 41 AM](https://user-images.githubusercontent.com/21169038/62226575-02763d80-b380-11e9-9675-9b4bd29d53df.jpg)
![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM7-31-2019-10 38 47 AM](https://user-images.githubusercontent.com/21169038/62226577-02763d80-b380-11e9-9c0c-3ed3decc3d9a.jpg)

**Comment by SourMesen** [comment]
Comparing frame rates isn't really indicative of accuracy.  bsnes has a lot of speed-focused options, I don't know which ones you have enabled, if any.  byuu has also spent a ton of time lately optimizing bsnes, whereas I'm still busy actually writing the emulation core - I can't spend all my time trying to optimize every single bit of code when I might need to rewrite that code in 2 weeks to add support for something else anyway. :p

Like I said, I'll take a look to see if those particular scenes do something specific that is causing a slowdown (e.g maybe there is a specific piece of code that's causing these slowdowns and can easily be optimized), but in general, performance varies greatly from one game to another, and also varies greatly within the same game (this is especially true for the super fx chip), so seeing a dip below 60 FPS in this case with the CPU you've mentioned before is not overly surprising at the moment.

**Comment by Cibomatto2002** [comment]
Found out it was some of the filters that was giving the slowdown like the xBRZ filters.

**Comment by SourMesen** [comment]
Ah, those scenes might have been in high resolution then (e.g 512x448) - that tends to make the xBRZ filter pretty slow.  Will probably have to add support for a multithreaded xBRZ filter eventually.

Thanks for reporting back!
