### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [SourMesen/Mesen-S#2]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [BaseVideoFilter](https://github.com/SourMesen/Mesen-S/blob/adcb6257f83f3052599b0673458e9d8ff5c918e5/Core/BaseVideoFilter.cpp#L16 "Destructor for BaseVideoFilter")
- [CamstudioCodec](https://github.com/SourMesen/Mesen-S/blob/adcb6257f83f3052599b0673458e9d8ff5c918e5/Utilities/CamstudioCodec.cpp#L8 "Destructor for CamstudioCodec")
- [ZmbvCodec::FreeBuffers](https://github.com/SourMesen/Mesen-S/blob/adcb6257f83f3052599b0673458e9d8ff5c918e5/Utilities/ZmbvCodec.cpp#L357 "ZmbvCodec::FreeBuffers function")

**Comment by SourMesen** [comment]
Fixed by 9a6087875181a9a9455477297a5b963f1b026387.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/SourMesen/Mesen-S/commit/9a6087875181a9a9455477297a5b963f1b026387 "Deletion of unnecessary checks").
