### ISSUE TITLE
[BUG - MINOR] Super Mario World 2 - Yoshi's Island // Level Select screen shaking when validating a level

### ISSUE THREAD

**Issue by Zet-sensei** [SourMesen/Mesen-S#20]
**Bug :** The map of the game is shaking one time when selecting a level on the level select screen.
**Expected behaviour :** The map should not shake at all.
**How to reproduce the bug :** Using the save state, validate the level to enter and the bug will appear on the left of the screen.

[Super Mario World 2 - Yoshi's Island (USA)_SaveState.zip](https://github.com/SourMesen/Mesen-S/files/3452987/Super.Mario.World.2.-.Yoshi.s.Island.USA._SaveState.zip)

Same problem happen on all regions and revisions of the game

**Comment by SourMesen** [comment]
I just tried reproducing something like what you described but couldn't see any difference compared to other emulators.
Is it possible that you have multiple SNES buttons binded to the same keyboard/gamepad key and choosing a stage also presses R or Start, which makes the map at the bottom start scrolling to the right?

**Comment by Zet-sensei** [comment]
Keyboard configuration on Key Set #2 (by default when first opening the emulator) was in conflict with my (reconfigured keyboard) configuration on Key Set #1.

Didn't see that there was TWO Key Sets already configured with the emulator on keyboard by default (and I needed to remove/clear the second one).

Issue closed.
