### ISSUE TITLE
Libretro - enhancement chips - Super Mario Kart

### ISSUE THREAD

**Issue by wwark** [SourMesen/Mesen-S#22]
Hi,

I have an issue to play Super Mario Kart (stuck in the nintendo logo) 
I put these files in system directory of Lakka TV
![image](https://user-images.githubusercontent.com/469461/62392291-6018ae80-b567-11e9-827e-9561c765af88.png)

Did I miss something ?
Thanks for your help !

**Comment by SourMesen** [comment]
You probably need to put the files in the subfolder named "Firmware" (inside the System folder)

**Comment by wwark** [comment]
It is working !
Thank you !
