### ISSUE TITLE
Enabling "Show game timer" crashes the emulator

### ISSUE THREAD

**Issue by victordg-github** [SourMesen/Mesen-S#23]
Congratulations on this amazing emulator! I'm enjoying it very much, although I think I found a small bug.

Enabling 'Tools > Preferences > Advanced > Show game timer' makes the emulator crash on next start. Most times just enabling it works fine during the running session. However the emulator won't start afterwards, unless disabled manually in settings.xml:
<ShowGameTimer>false</ShowGameTimer> or delete de settings.xml as if it was a new setup.

Using Linux x64 compiled from source. Tried several updates since 0.20.0.10 to latet.

**Comment by SourMesen** [comment]
Happy to hear you like the emulator!  And thank you for the report.  

This should be fixed by 7e854b4376529f33e8789ffcdb0088e337ed12a6

**Comment by victordg-github** [comment]
Awesome! Thanks for the quick fix, it's not crashing anymore.
