### ISSUE TITLE
SMW2: Yoshi's Island - Broken Effects

### ISSUE THREAD

**Issue by BigheadSMZ** [SourMesen/Mesen-S#25]
Just wanted to say, thank you for this amazing emulator so far. I only use Mesen for NES emulation and I'm sure Mesen-S will replace all my other SNES emulators eventually. :)

So with that said, I noticed some potential layering and transparency issues with this title. World 1-2, after bouncing on the up arrow ball, there is a layer of the foreground that should vanish/appear as you enter/exit it. Currently it fades out correctly, but it doesn't fade back in.

![](https://i.imgur.com/QdsMFGx.png)

Before it fades out, I noticed that my star counter was falling behind the foreground in some spots. I'm assuming both issues are one in the same.

![](https://i.imgur.com/IPvYiGB.png)

**Comment by SourMesen** [comment]
Thanks for the report!
I took a quick look, so far it looks like the star counter issue is "normal" - the same happens in bsnes-plus and it seems like a pretty simple case of layer drawing priority.. I might double-check in higan/bsnes to be 100% sure, though.

The layer fading out and not coming back definitely looks like a bug though - I'll try to take a look soon.

**Comment by SourMesen** [comment]
Well, it sure took me a long time to find what ended up being a pretty silly mistake.
This should be fixed as of 973a59a027b82ffbde191406e57f5027d1f54b01.
Let me know if you find anything else!

**Comment by BigheadSMZ** [comment]
Can confirm it's fixed now, thank you and will do!
