### ISSUE TITLE
firmware list

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#26]
PLease supply a list of supported firmware roms.

seems cx4.rom not required or supported (using HLE emulation?)

dsp1b.rom is required and supported.

WHat else?

Thank you

**Comment by SourMesen** [comment]
The supported firmwares and their filenames (split or combined) can be found here:
https://github.com/SourMesen/Mesen-S/blob/master/Core/NecDsp.cpp#L84

CX4 is LLE - the so-called "firmware" is just a lookup table of mathematical constants, not code.

**Comment by ghost** [comment]
Thanks for the help! Just wanted to make sure I set up my mesen-s correctly!


For such a young emulator it is very impressive already!


Thanks very much!

**Comment by ghost** [comment]
is there any advantage/disadvantage to go split or combined? I think no but curious.

**Comment by SourMesen** [comment]
No, they're the same. Split roms are supported because they are what bsnes/higan use.  Combined roms are supported because it's easier to ask the user to select a single file, rather than making them select 2 separately (the UI will prompt you for a firmware file if it can't find it)

**Comment by ghost** [comment]
> No, they're the same. Split roms are supported because they are what bsnes/higan use. Combined roms are supported because it's easier to ask the user to select a single file, rather than making them select 2 separately (the UI will prompt you for a firmware file if it can't find it)

Thanks for the clarity

**Comment by SourMesen** [comment]
You're welcome!
