### ISSUE TITLE
Video Output 4:3 and 8:7 ratios produce wider than expected image

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#27]
Video Output 4:3 and 8:7 ratios produce wider than expected image

**Comment by Lululalu** [comment]
I may be wrong, but I believe mesen cuts the overscan off after the aspect ratio is stretched.

**Comment by ghost** [comment]
Well the 8:7 and 4:3 modes look wrong even when compared to it's older brother Mesen. I think something is wrong. Not complaining only reporting because I am liking mesen-s alot. It's shaping up to be the only SNES emulator to use in my current opinion.
