### ISSUE TITLE
Advancing a scanline over the edge of the screen whilst the event viewer is open causes crash

### ISSUE THREAD

**Issue by Molive-0** [SourMesen/Mesen-S#31]
To repoduce:
Open a game, the CPU Debugger and the Event viewer.
Hold F7 in the debugger and watch the yellow scanline indicator move down the event viewer.
When the line hits the bottom of the screen, Mesen-S crashes.

![image](https://user-images.githubusercontent.com/23285288/63654476-8ac6e300-c772-11e9-9101-f4d30268cad2.png)

**Comment by SourMesen** [comment]
Sorry for the super long delay!

Just tried to reproduce this, but I haven't been able to.  Any chance you could try this on the latest appveyor dev builds and see if you can still get it to crash on your end?

**Comment by Molive-0** [comment]
Can confirm this crash happens in the latest version of the emulator pulled from appveyor, built six hours ago. Will create a video of crash happening.

**Comment by Molive-0** [comment]
Video:
[2019-10-08 09-39-51.zip](https://github.com/SourMesen/Mesen-S/files/3701493/2019-10-08.09-39-51.zip)

**Comment by SourMesen** [comment]
Finally figured it out - it crashed in PAL mode, but not NTSC.
Should be fixed now (and the event viewer will display the ~310 PAL scanlines rather than just the ~262 scanlines it was displaying in PAL mode before)
