### ISSUE TITLE
Super Offroad

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#36]
Does this emulator support this title correctly?

Memory randomization?

**Comment by Cibomatto2002** [comment]
I think so.
![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM9-11-2019-11 20 54 PM](https://user-images.githubusercontent.com/21169038/64754425-e7552c80-d4ec-11e9-8569-59b1829e6ee1.jpg)

**Comment by ghost** [comment]
> I think so.
> ![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM9-11-2019-11 20 54 PM](https://user-images.githubusercontent.com/21169038/64754425-e7552c80-d4ec-11e9-8569-59b1829e6ee1.jpg)

I saw this so I assumed yes but I dunno if that is enough to know. I figured ide ask and see what Sour says.

**Comment by bachimusprime** [comment]
You know, you could just try it and see.

**Comment by ghost** [comment]
I did try it. Seems fine. However I'm curious if I'm witnessing memory randomization or game specific hack..

**Comment by SourMesen** [comment]
Sorry for the late reply - the default behavior is to randomize all RAM at power on (this should be applied to pretty much every type of memory on the system as far as I know.)  This is the same behavior as higan/bsnes afaik.

Was there a specific issue with this game?

**Comment by ghost** [comment]
on some emulators like snes 9x the game becomes super easy due to no memory randomization, power ups always appear in the same place driver ai is dumbed down.

in higan performance is proper as real hardware. snes9x, snes mini and most emulators require a patch to kind of fix the game found on rom hacks.

I believe the behaviour is proper in mesen-s

this game is a problem game that can be used to make sure the emulator is using proper memory randomization.

in the past the only way to play this proper was real hardware or higan.


And please dont say sorry for the late reply. You have given two amazing emulators to the comm=unity if anything thank you for your time/efforts/part of your life.

**Comment by ghost** [comment]
more description 

Some games such as Super Off Road use system RAM as a random number generator for item placement and AI behavior to make gameplay more unpredictable.

**Comment by SourMesen** [comment]
Thanks for the clarification! In that case, yes, it should be behaving correctly in Mesen-S.

**Comment by ghost** [comment]
to be more clear I found this 

Dumb AI. Lackluster bonus item placement.
Same, same. Easy CPU with no nitro? Something stinks. Another
copy protection that ucon64 missed?


Find when AI does nitro:
$00/A65A 20 C2 99    JSR $99C2  [$00:99C2]   A:0350 X:0002 Y:0001 D:0000 DB:00 S:01F4 P:envMXdIzc
$00/A65D C5 54       CMP $54    [$00:0054]   A:03D7 X:0002 Y:0001 D:0000 DB:00 S:01F4 P:eNvMXdIzc
$00/A65F B0 20       BCS $20    [$A681]      A:03D7 X:0002 Y:0001 D:0000 DB:00 S:01F4 P:eNvMXdIzC


cpu nitro
$00/A661 DA          PHX                     A:0442 X:0003 Y:0000 D:0000 DB:00 S:01F4 P:eNvMXdIzc
$00/A662 A6 5C       LDX $5C    [$00:005C]   A:0442 X:0003 Y:0000 D:0000 DB:00 S:01F3 P:eNvMXdIzc
$00/A664 A9 FF       LDA #$FF                A:0442 X:0006 Y:0000 D:0000 DB:00 S:01F3 P:envMXdIzc
$00/A666 9D 11 05    STA $0511,x[$00:0517]   A:04FF X:0006 Y:0000 D:0000 DB:00 S:01F3 P:eNvMXdIzc
$00/A669 9D 12 05    STA $0512,x[$00:0518]   A:04FF X:0006 Y:0000 D:0000 DB:00 S:01F3 P:eNvMXdIzc
$00/A66C FA          PLX                     A:04FF X:0006 Y:0000 D:0000 DB:00 S:01F3 P:eNvMXdIzc
$00/A66D 80 12       BRA $12    [$A681]      A:04FF X:0003 Y:0000 D:0000 DB:00 S:01F4 P:envMXdIzc


rng
====>
$00/99C2 DA          PHX                     A:0200 X:0003 Y:0000 D:0000 DB:00 S:01F2 P:envMXdIZC
$00/99C3 08          PHP                     A:0200 X:0003 Y:0000 D:0000 DB:00 S:01F1 P:envMXdIZC
$00/99C4 E2 20       SEP #$20                A:0200 X:0003 Y:0000 D:0000 DB:00 S:01F0 P:envMXdIZC
$00/99C6 66 51       ROR $51    [$00:0051]   A:0200 X:0003 Y:0000 D:0000 DB:00 S:01F0 P:envMXdIZC

$00/99C8 A5 50       LDA $50    [$00:0050]   A:0200 X:0003 Y:0000 D:0000 DB:00 S:01F0 P:eNvMXdIzc
$00/99CA 48          PHA                     A:0200 X:0003 Y:0000 D:0000 DB:00 S:01F0 P:envMXdIZc
$00/99CB 6A          ROR A                   A:0200 X:0003 Y:0000 D:0000 DB:00 S:01EF P:envMXdIZc
$00/99CC 85 51       STA $51    [$00:0051]   A:0200 X:0003 Y:0000 D:0000 DB:00 S:01EF P:envMXdIZc

$00/99CE A5 4F       LDA $4F    [$00:004F]   A:0200 X:0003 Y:0000 D:0000 DB:00 S:01EF P:envMXdIZc
$00/99D0 AA          TAX                     A:02E2 X:0003 Y:0000 D:0000 DB:00 S:01EF P:eNvMXdIzc
$00/99D1 0A          ASL A                   A:02E2 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:eNvMXdIzc
$00/99D2 0A          ASL A                   A:02C4 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:eNvMXdIzC
$00/99D3 0A          ASL A                   A:0288 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:eNvMXdIzC
$00/99D4 0A          ASL A                   A:0210 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIzC
$00/99D5 85 50       STA $50    [$00:0050]   A:0220 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIzc

$00/99D7 A5 4E       LDA $4E    [$00:004E]   A:0220 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIzc
$00/99D9 85 4F       STA $4F    [$00:004F]   A:0205 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIzc

$00/99DB 4A          LSR A                   A:0205 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIzc
$00/99DC 4A          LSR A                   A:0202 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIzC
$00/99DD 4A          LSR A                   A:0201 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIzc
$00/99DE 4A          LSR A                   A:0200 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIZC
$00/99DF 05 50       ORA $50    [$00:0050]   A:0200 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIZc
$00/99E1 45 51       EOR $51    [$00:0051]   A:0220 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIzc
$00/99E3 86 50       STX $50    [$00:0050]   A:0220 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIzc

$00/99E5 A6 4D       LDX $4D    [$00:004D]   A:0220 X:00E2 Y:0000 D:0000 DB:00 S:01EF P:envMXdIzc
$00/99E7 86 4E       STX $4E    [$00:004E]   A:0220 X:00AA Y:0000 D:0000 DB:00 S:01EF P:eNvMXdIzc
$00/99E9 85 4D       STA $4D    [$00:004D]   A:0220 X:00AA Y:0000 D:0000 DB:00 S:01EF P:eNvMXdIzc
$00/99EB 68          PLA                     A:0220 X:00AA Y:0000 D:0000 DB:00 S:01EF P:eNvMXdIzc
$00/99EC 85 51       STA $51    [$00:0051]   A:0200 X:00AA Y:0000 D:0000 DB:00 S:01F0 P:envMXdIZc

$00/99EE 28          PLP                     A:0200 X:00AA Y:0000 D:0000 DB:00 S:01F0 P:envMXdIZc
$00/99EF FA          PLX                     A:0200 X:00AA Y:0000 D:0000 DB:00 S:01F1 P:envMXdIZC


$00/99F0 A5 4D       LDA $4D    [$00:004D]   A:0200 X:0003 Y:0000 D:0000 DB:00 S:01F2 P:envMXdIzC
$00/99F2 60          RTS                     A:0220 X:0003 Y:0000 D:0000 DB:00 S:01F2 P:envMXdIzC



A random number generator. Funny to note is it's never
seeded. Relies on startup uninitialized ram. Snes9x = 55 55 55 55.
Canoe likely similar. Snes9x isn't fun to play either. What to do?

Jinx the numbers ourself. Note how ram $0b,$0d acts like in-game
timer but not fully tied to each other. Can deviate each other.
So that's our unpredictable spot. Choose a pre-race spot that
runs every time. Like when screen is turned off for loading.


$00/A428 E2 20       SEP #$20                A:FFFF X:02E8 Y:0100 D:0000 DB:00 S:01F6 P:eNvMxdIzc HC:0684 VC:234 FC:44 I:00
$00/A42A A9 80       LDA #$80                A:FFFF X:02E8 Y:0100 D:0000 DB:00 S:01F6 P:eNvMxdIzc HC:0714 VC:234 FC:44 I:00

$00/A42C 8D 00 21    STA $2100  [$00:2100]   A:FF80 X:02E8 Y:0100 D:0000 DB:00 S:01F6 P:eNvMxdIzc HC:0738 VC:234 FC:44 I:00
==> JSR seed

$00/A42F 20 6F B4    JSR $B46F  [$00:B46F]   A:FF80 X:02E8 Y:0100 D:0000 DB:00 S:01F6 P:eNvMxdIzc HC:0776 VC:234 FC:44 I:00




org $ffa0

seed:
sta $2100


lda $0b
sta $4d

lda $0d
sta $50

jsr $99c2
lsr
sta $4f

jsr $99c2
asl
sta $51

rts


This jiggles the rng enough to create some volatile
starting numbers. Note that routine can get "stuck"
over long time and start churning dumb patterns.
Or given bad initial seeds (55 55 55 55).

New code uses some uninit values + in-game timers
before every race. Keeps things fresh and plays good
enough overall. Creates some values that rng may not
generate in self-feedback lifespan.


Stupid rng problem can happen on real hardware too,
but more rare.
