### ISSUE TITLE
Minor sound issues

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#38]
This is probably known since the emulator is still young, but sometimes the beginning of sound bytes are a little chopped off when they play, be it just sound effects or music when it begins to play.

If there is a way to fix this by adjusting the latency, I'd like to know.  The buffer size in Snes9x is 64 by default and I notice it is 60 in Mesen-S.

**Comment by SourMesen** [comment]
I haven't personally noticed too many sound issues on my end, but this is the kind of stuff that can vary a lot from one PC to the other.  Are you on Windows?
Have you tried increasing the latency in the audio options?

In preferences->advanced, there is an option to display some debug information on the screen, there's an "underrun" value in the debug info, does its value keep increasing?  If so, does it happen at the same time as the sound issues you're hearing?

**Comment by obunden** [comment]
@84L7H13R did you solve the problem?

Audio issues might be due to to audio drivers or which audio API  you are using (or computer performance in general). I'm not hearing anything odd in linux (using retroarch) with pulseaudio personally.

**Comment by SourMesen** [comment]
Would need more information to do anything about this - closing for now, let me know if you still have issues.
