### ISSUE TITLE
First Samurai (USA) - fast forward function skips intro cutscene

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#39]
![image](https://user-images.githubusercontent.com/53529402/64996666-dcc8d780-d8de-11e9-9888-5c020885b045.png)

**Comment by SourMesen** [comment]
Fast forward doesn't seem to be causing any issues for me here.  You might have some conflicting keybindings setup?  e.g fast forward might be some buttons on P1 or P2's controller, etc?

**Comment by Max833** [comment]
Yeah, you're right. Conflicting keybindings setup. :-/ Sorry!

**Comment by SourMesen** [comment]
No problem!
