### ISSUE TITLE
Jimmy Connors Pro Tennis Tour (USA)

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#42]
Start a game, press start and you see a weird effect on the upper edge. No problems with bsnes, snes9x and on hardware.

![image](https://user-images.githubusercontent.com/53529402/66164654-727c9a80-e633-11e9-9cc2-12aecf250647.png)

**Comment by SourMesen** [comment]
Thanks for the report!
This was a bug with the mosaic implementation, should be fixed as of 3df7a209763881076cab7b2bc1a560fc6406af90 (which hopefully hasn't caused any regressions - I've tested a few of the tests/games that I've had mosaic issues with before and they seemed to behave correctly)
