### ISSUE TITLE
Tengai Makyou Zero (Japan)

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#44]
bsnes: 
![image](https://user-images.githubusercontent.com/53529402/66256322-f72efc00-e78c-11e9-99ed-49b66a488018.png)

Mesen-S:
![image](https://user-images.githubusercontent.com/53529402/66256325-fe560a00-e78c-11e9-89c5-62c48d082852.png)

**Comment by SourMesen** [comment]
This one is actually expected - the SPC7110 isn't supported yet.
