### ISSUE TITLE
RetroArch iOS copies the wrong filename

### ISSUE THREAD

**Issue by jet082** [SourMesen/Mesen-S#45]
Right now, it copies the wrong file name, which forces it to fail compiling.

To fix, change the following in the Makefile:

```
else ifneq (,$(findstring ios,$(platform)))
   TARGET := $(TARGET_NAME)_libretro.dylib

to

else ifneq (,$(findstring ios,$(platform)))
   TARGET := mesens_libretro_ios.dylib
```

Then it works.

**Comment by jet082** [comment]
This is fixed by https://github.com/SourMesen/Mesen-S/pull/46

**Comment by SourMesen** [comment]
This is hopefully fixed by your PR - let me know if you still have issues with it!

**Comment by jet082** [comment]
Everything works great!

**Comment by SourMesen** [comment]
Unfortunately it looks like it did break at least some of the other builds:
```
COPY CMD: cp ./mesen-s_libretro.dll /home/buildbot/buildbot/windows_x86/dist/win_x86//mesen-s_libretro.dll
cp: cannot stat './mesen-s_libretro.dll': No such file or directory
```

**Comment by jet082** [comment]
Ergh. That's unfortunate. One alternative we could do, is to make a copy of the file to both locations. Then it would not matter and the official script + the buildbots (which must use some other system) could work.

**Comment by jet082** [comment]
(Or, alternatively, if there is a way to detect either the buildbots or the official build scripts - that could work as well)

**Comment by SourMesen** [comment]
I've added an extra copy operation at the end of the makefile, so it always produces both the "mesen-s" and "mesens" files. Hopefully this works for all scenarios.

Not quite sure why it was behaving differently from one system to another in the first place, though, but if this works, it'll be good enough for now :p
