### ISSUE TITLE
Save/Load command occasionally gets "Stuck" and executes the wrong function.

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#47]
This one's a bit hard to explain, but I'll do the best I can. 

Occasionally, when trying to load a state, the "SAVE" function gets executed instead. I'm using the default shortcuts for this (Shift + F keys to save, F keys to load), while also extending them out to F8-F10. I've noticed that it thinks the Shift is held, when its not (and no, it's not my keyboard to my knowledge, I've tested that too). While in this odd phase where the error has at least once occurred, if I continue to press F10 again in an attempt to load, it will continously keep saving.

The only way I've found that I can break out of this behavior is to press "SHIFT" as a standalone. Then when I go to load, it'll work correctly.  I used my keyboard's opposite shift key when doing this, as opposed the one I normally use, just to make sure.

**Comment by ghost** [comment]
It appears as this though this is triggering at the highest frequency with the F10 key. 

P.S. Although in its infancy, this is one of the best SNES emulators I've seen so far. Has all the features, debugging tools, and SUPER high customization ability. The "MESEN" emulators kick ass, keep up the great work!

**Comment by SourMesen** [comment]
Thanks for the report!
I think the behavior was exclusive to the F10 key.  Windows in general uses that key to focus on the menu bar/etc in applications, which seems like it was causing problems.  I disabled the default windows behavior for that key and the shift key no longer gets "stuck" after using Shift+F10.  This fixes the slight glitch that occurred when trying to add a keybinding that used the F10 key, too.
(Also fixed the same bug in Mesen, too)

And thanks!  Happy to hear you're liking Mesen(-S)!
