### ISSUE TITLE
Feature Request: Show HUD text when toggling BG & Sprite layers on/off

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#50]
Hello again,

A quick feature request here. Having a HUD appear when you toggle BG & Sprite layers on/off would be great! Sometimes in certain areas and games, you literally cannot tell if something is on or off until you move around, which isn't always ideal. The text overlay area for when saves get loaded/saved would work just fine.

Please consider. Cheers & Thanks!

**Comment by SourMesen** [comment]
Thanks for the request!

Apparently I'm just one step ahead of you, because I added this a few days ago :p (https://github.com/SourMesen/Mesen-S/commit/accac0f21e6bc7967786db20eef962e08b84a3f1)

If you grab the latest dev build, it should work.

**Comment by ghost** [comment]
Sweet! Thanks mate.
