### ISSUE TITLE
0.3.0 release makefile tries to use msbuild on linux

### ISSUE THREAD

**Issue by mankeli** [SourMesen/Mesen-S#51]
```
$ make --trace
makefile:95: update target 'ui' due to: InteropDLL/obj.x64/libMesenSCore.x64.dll
mkdir -p bin/x64/Release/Dependencies
rm -fr bin/x64/Release/Dependencies/*
cd UpdateHelper && msbuild /property:Configuration="Release" /property:Platform="AnyCPU"
/bin/sh: 1: msbuild: not found
makefile:95: recipe for target 'ui' failed
make: *** [ui] Error 127
```

**Comment by 1985a** [comment]
you should update msbuild
if you are on archlinux, remove your actual msbuild, then install yay -S msbuild-16-bin

**Comment by SourMesen** [comment]
This is normal - `msbuild` is available on Linux too.  Previously this used to use `xbuild`, but the later versions of xbuild contained a warning that xbuild was deprecated and people should use msbuild instead, so I updated the makefile to using msbuild instead.

I believe there are (unfortunately) 2 different versions of msbuild available on Linux (that, or they've stripped out some functionality from newer versions?), and one of them doesn't work when trying to compile Mesen(-S).

The version I'm using locally is: `Microsoft (R) Build Engine version 15.6.0.0 ( Fri Apr  6 15:55:10 UTC 2018) for Mono`

You can also try using xbuild if you have it installed, by slightly changing the makefile (e.g do the opposite of this commit: https://github.com/SourMesen/Mesen/commit/babbec7d12ced3b1eca418c4e5fc834ced6bca06#diff-cd5dbf3629c558b0104ba8f0937d6816)

Hope that helps!

**Comment by SourMesen** [comment]
For now, the makefile was reverted to using xbuild rather than msbuild, since it tends to come preinstalled with mono, unlike msbuild.
