### ISSUE TITLE
Sugoi Hebereke (Japan) - The first arena has no fog/haze

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#53]
bsnes:
![image](https://user-images.githubusercontent.com/53529402/67801725-166a3200-fa8a-11e9-87b1-07af146b8a9a.png)

Mesen-S - doesn't have fog/haze:
![image](https://user-images.githubusercontent.com/53529402/67801745-21bd5d80-fa8a-11e9-91e4-1640482d52f7.png)

**Comment by Max833** [comment]
Ups, I didn't enable "Blend High resolution Modes". Sorry! :)

![image](https://user-images.githubusercontent.com/53529402/67802106-d192cb00-fa8a-11e9-9f10-f210e5e62541.png)

**Comment by SourMesen** [comment]
Actually, as far as I can tell, it looks like the arena has random "weather" each time it starts?  Sometimes it's rain, sometimes it's foggy - it doesn't seem like it's using high resolution modes to make some fake transparency though, the option doesn't seem to have any impact on the fog's appearance on my end.

**Comment by Max833** [comment]
You're absolutely right.
