### ISSUE TITLE
Text invisible in ActRaiser 2 with 0.3.0 Release

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#54]
Several areas that are supposed to display text in the game ActRaiser 2 are not doing so. They have invisible text in the 0.3.0 release, whereas in version 0.2.0 they displayed just fine.

Here's some screenshots to show what I mean. The first image is with version 0.3.0, and the second is 0.2.0:
![ActRaiser 2 (USA)_000](https://user-images.githubusercontent.com/6374154/67819453-65a46880-fa72-11e9-8c80-c0285dac2e15.png)

![ActRaiser 2 (USA)_000](https://user-images.githubusercontent.com/6374154/67819465-6f2dd080-fa72-11e9-8983-f7727845b2dd.png)

In both instance I'm loading the rom from a ZIP archive, and additionally my 0.3.0 release was upgraded from a 0.2.0 one, if that helps.

**Comment by SourMesen** [comment]
Thanks for the report - this seems to be working properly on my end though.  My best guess at the moment is that you might have BG layer 3 disabled? (your first screenshot is exactly what I get if I disable it)

**Comment by ghost** [comment]
AAh, absolutely right! Really sorry about that, I'm surprised those layer toggles persist through application exits / restarts. I'll close the thread now. My apologies!
