### ISSUE TITLE
Kaite Tsukutte Asoberu Dezaemon (Japan)

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#58]
You can't reset the game because Mesen-S freezes right here:

![image](https://user-images.githubusercontent.com/53529402/68078287-493a6000-fdd3-11e9-9a84-4a0c44111a61.png)

**Comment by SourMesen** [comment]
Thanks for the report!
Looks like I was being a bit too conservative on what to reset when resetting the SPC - this is fixed by 8327ec501d6014b50dc609eba8ff0fdb3f2e45d0
