### ISSUE TITLE
A.S.P. - Air Strike Patrol (USA)

### ISSUE THREAD

**Issue by nonochus** [SourMesen/Mesen-S#59]
With the latest versions of Mesen the game shows graphic errors, with the previous versions it did not happen. It is clearly seen before starting the missions, when it is explained what needs to be done, the letters look bad.
![A S P  - Air Strike Patrol (USA)_001]

(https://user-images.githubusercontent.com/57305919/68079022-8b1ed280-fde2-11e9-8921-f28a58b00934.png)

**Comment by SourMesen** [comment]
Thanks for the report!

This is fixed by f91e2066365ba871db47c9a8a2ea31c6c5f5f3ce - the next appveyor dev build should be working properly.
