### ISSUE TITLE
Loading a save state while debugging hangs the emulator.

### ISSUE THREAD

**Issue by tewtal** [SourMesen/Mesen-S#6]
While debugging, trying to load a save state to go back to a previous state causes the emulator to just hang forever.

Steps to reproduce:

- Create a save state
- Open the debugger and break execution
- Load the previously saved state without hitting Continue

**Comment by SourMesen** [comment]
Thanks for the report - this should be fixed by dbafe258b22563f6cb3f74b670670b3b51f3a889
