### ISSUE TITLE
Shin Nihon Pro Wrestling Kounin - '95 Tokyo Dome Battle 7 (Japan)

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#66]
https://github.com/byuu/bsnes/issues/214

**Comment by SourMesen** [comment]
Thanks! This is fixed by 3d079f66d7df0f17c281f2bfe448a059b9638d61

**Comment by Max833** [comment]
Maybe this one is important in the future, so... here is a link that works: https://archive.is/o/Ghl0y/https://github.com/byuu/bsnes/issues/214
