### ISSUE TITLE
Power Drive (Europe) (En,Fr,De,Es,Pt) - glitches

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#67]
bsnes:
![image](https://user-images.githubusercontent.com/53529402/68502319-74ec9880-0260-11ea-917d-a69b4065844d.png)

Mesen-S:
![image](https://user-images.githubusercontent.com/53529402/68502336-7b7b1000-0260-11ea-90ab-d45e77373287.png)

**Comment by FitzRoyX** [comment]
This game and Death Brade (J) require WRAM to be initialized to 0x55

**Comment by SourMesen** [comment]
Looks like you have the power on RAM set to be all 0s (the default is random values), or you got extremely unlucky with the random values you got :p

Good to know this and Death Brade need non-0 values, though.  Will probably need to have an extra option in the dropdown eventually to pick the "best" option based on a database of sorts.

**Comment by obunden** [comment]
Works in Mesen 0.3.0 (libretro) with default settings

**Comment by SourMesen** [comment]
I've added overrides for both of these games for now to force them to init ram to $FF.
Eventually, a database of games that need a specific pattern on power on would probably be useful, but this will do for now.
