### ISSUE TITLE
Cheat Toggle command isn't working as intended.

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#72]
Hello again!

Here to report that the cheat toggle hotkey isn't working as intended. I maped the Enable/Disable Cheats shortcut to Shift + C. I have one cheat enabled for the ROM, Arcana (USA).sfc, which is a Pro Action replay code that contains the following:

7E13A3FD
7E13A4E8

When I press the toggle, it turns the cheats OFF and then ON rapidly, each time I press it. So it's currently only really acting as an ON switch (but wont work at all if you don't have the cheats enabled from the Cheat menu, which I believe you did intentionally). 

I can provide a video if needed. I tested the code with only 1 line, the result was the same. 

----

Additionally, I got back to you on two other Mesen-S issues a few weeks back. Not sure if you overlooked them or are really busy, but I'll post those here.

1) https://github.com/SourMesen/Mesen/issues/712
2) https://github.com/SourMesen/Mesen/issues/616

---

Thank you for your hard work!!

**Comment by SourMesen** [comment]
Thanks for the reports. I was away on a bit of a holiday for the past week or so.
This is fixed by 7f805b9a62dd6542655876da094fe3584d719533

**Comment by ghost** [comment]
Excellent work!
