### ISSUE TITLE
FPS is limited and locked with cheats enabled, also fast forward not working while on. 

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#73]
While running the cheat code described here:
https://github.com/SourMesen/Mesen-S/issues/72

... I noticed that the FPS is getting limited to around 40 FPS instead of 60. Additionally, fast forward settings do not work. The FPS is locked at around a hard 40 FPS while cheats are on, and it's a bit choppy. Not sure what is going on.

Cross-tested this on Snes9X and Bsnes to see if it was this cheat / game combo specifically. It worked normally on those two emulators (with fast forward).

**Comment by SourMesen** [comment]
Thanks - this should be fixed by 6e70ab88dee573ff29230a57c5c4a1a8aa6e3b15, it was a performance issue that caused the emulator to run easily 2-3x slower when enabling codes in the 7Exxxx-7Fxxxx range.

**Comment by ghost** [comment]
You rock!
