### ISSUE TITLE
Graphical glitches - Clock Tower English translation 1.01

### ISSUE THREAD

**Issue by levonnn** [SourMesen/Mesen-S#74]
Having text glitches in the unofficial translation. Everything seems to be normal in the original Japanese version. Tried it on bsnes, translation works fine.

https://imgur.com/mwMgsev

**Comment by SourMesen** [comment]
Thanks for the report!
As far as I can tell, though, this looks like it's normal.
The patch isn't clearing the contents of memory correctly and expects the RAM to be filled with 0s at power on.  If you set the power on RAM to "All 0s", the glitches will disappear (in Options->Emulation->Advanced)

**Comment by levonnn** [comment]
This settles it, then. :) Thanks.

**Comment by SourMesen** [comment]
No problem!
