### ISSUE TITLE
[Lua] Inline help text issue.

### ISSUE THREAD

**Issue by SpiderDave** [SourMesen/Mesen-S#77]
The inline help text for addEventCallback and removeEventCallback references nonexistant enum "eventCallbackType".  Looks like it should be "eventType".  (The online docs don't have this issue).

https://github.com/SourMesen/Mesen-S/blob/aa3975aa1edfe5c025822a65f541eaa8493e10ba/UI/Debugger/Scripts/frmScript.cs#L495

https://github.com/SourMesen/Mesen-S/blob/aa3975aa1edfe5c025822a65f541eaa8493e10ba/UI/Debugger/Scripts/frmScript.cs#L496

**Comment by SourMesen** [comment]
Thanks!  This is fixed
