### ISSUE TITLE
Super Keiba 2 (Japan)

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#79]
Start the game and press A repeatedly and you will see a blackscreen.

**Comment by SourMesen** [comment]
Thanks for the report!  This is fixed by cdd5edba387fc2d895265b2519ef6ebd4804c2c5
Basically, there was a bug that caused SRAM to always be initialized with 0s (no matter the power on state setting), and this game has issues when SRAM is filled with 0s.
