### ISSUE TITLE
[Lua] emu.getState()  returns PPU H-Clock instead of scanline.

### ISSUE THREAD

**Issue by tewtal** [SourMesen/Mesen-S#80]
There's a problem in the getState() Lua function that overwrites the scanline count with the H-Clock due to the same name being used in the code.

From LuaApi::GetState:

lua_pushintvalue(scanline, state.Ppu.Scanline);

lua_pushintvalue(scanline, state.Ppu.HClock);

**Comment by SourMesen** [comment]
Thanks for the report! This is fixed.
