### ISSUE TITLE
Tintin in Tibet (Europe) (En,Es,Sv) - doesn't start

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#81]
https://github.com/byuu/bsnes/issues/260

![image](https://user-images.githubusercontent.com/53529402/71543125-e4812900-296f-11ea-8ae7-90c83a0b04c2.png)

It works when I load the rom manual and choose PAL instead of AUTO or with higan 106.

**Comment by SourMesen** [comment]
Thanks for the report!
This is fixed by fde27d6115476d8dbe4b812b2f18777eb877c0b8
