### ISSUE TITLE
Editing the "CPU Memory" while the emulator is paused causes a crash.

### ISSUE THREAD

**Issue by tewtal** [SourMesen/Mesen-S#84]
When editing memory using the "CPU Memory" view the emulator crashes if the emulator is paused.

Only the "CPU Memory" view seems affected from what I can tell. Editing RAM using the "Work RAM" view still works when paused, and the same with "PRG ROM" for example.

**Comment by SourMesen** [comment]
Thanks for the report!
This is fixed by 065a09c532d225ace317a121771c541968fca874
