### ISSUE TITLE
Terranigma is completely broken.

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#85]
The wrong letters are loaded.

![Capture](https://user-images.githubusercontent.com/31968468/71814951-1150e100-30d2-11ea-8aec-8ce1c94e5b87.PNG)

![Capture2PNG](https://user-images.githubusercontent.com/31968468/71814964-1746c200-30d2-11ea-98eb-61dbe57308c2.PNG)

And then the graphics shit themselves.

![Capture3](https://user-images.githubusercontent.com/31968468/71814979-2299ed80-30d2-11ea-95f6-b7affcc2ec57.PNG)

![Capture4](https://user-images.githubusercontent.com/31968468/71814991-2a599200-30d2-11ea-9274-1b4349262e3c.PNG)

I'm playing with a patch that converts the game from PAL to NTSC but I can't imagine that would cause this sort of nonsense.

**Comment by Max833** [comment]
> I'm playing with a patch that converts the game from PAL to NTSC but I can't imagine that would cause this sort of nonsense.

Yes, wrong letters are loaded with the original version as well. But ingame... I don't have problems with this version.

![image](https://user-images.githubusercontent.com/53529402/71816072-c0190100-3081-11ea-8fae-ce3f5446f20b.png)

**Comment by ghost** [comment]
It didn't happen immediately. I'd been playing for about 5 or 10 minutes, entered a house, came out and then it happened.

**Comment by SourMesen** [comment]
I haven't been able to reproduce this specific issue, but I did notice another issue that caused temporary sprite corruption on some frames.  This is fixed by 24beded73db0a288b3c7750e7d640f3807e4ea8f, and may fix this as well (assuming you were using a fairly recent dev build.)

Can you test if you still have issues in the latest dev build?

**Comment by ghost** [comment]
Both the incorrect text and the broken sprites are now fixed. Thanks.
