### ISSUE TITLE
Mosaic emulation

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#89]
https://github.com/byuu/bsnes/issues/278

Maybe you can help byuu with this. With Mesen-S Jurassic Park Part 2 has some issues as well. 

hardware video: https://streamable.com/gjjgp

Mesen-S:
![image](https://user-images.githubusercontent.com/53529402/72217234-e9c3a380-352b-11ea-9247-c3ab52f7c5e0.png)

**Comment by SourMesen** [comment]
Did you try this with the latest dev build? I was playing FF6 yesterday and happened to find 2 separate mosaic issues that I fixed.
As far as I can tell using the latest build, I'm seeing exactly the same sequence of mosaic blocks as what I can see in your hardware recording.

**Comment by Max833** [comment]
I downloaded 0.3.0.29 yesterday. What a timing... 0.3.0.30 fixed this indeed.

**Comment by SourMesen** [comment]
Thanks for the confirmation!
