### ISSUE TITLE
A.S.P. - Air Strike Patrol (USA)

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#92]
The lines in the pause screen aren't completely visible on the right hand side. With bsnes it's the other way around and on hardware and bsnes 0.73 it looks fine. 

![ds](https://user-images.githubusercontent.com/53529402/72645790-bb532780-3974-11ea-9566-23a3d97adf75.png)
Hardware:
![sd](https://user-images.githubusercontent.com/53529402/72645815-c9a14380-3974-11ea-89fc-ba09e761974e.jpeg)
bsnes 0.73
![image](https://user-images.githubusercontent.com/53529402/72646041-682da480-3975-11ea-9ae3-6cec216d9ac9.png)

**Comment by SourMesen** [comment]
Thanks for the report!

This is fixed - see comment in #91
