### ISSUE TITLE
Aging Cassette (Japan)

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#94]
For like 1 frame you can see this here:

Mesen-S:
![image](https://user-images.githubusercontent.com/53529402/73091013-cf99a600-3ed9-11ea-8fe6-03320788b2ad.png)

bsnes:
![image](https://user-images.githubusercontent.com/53529402/73091039-db856800-3ed9-11ea-99cc-5ca83b65e89b.png)

**Comment by SourMesen** [comment]
Thanks - this was a display bug when switching from regular to interlace display.  Also affected the 240p test rom, but I hadn't investigated properly until now.
This is fixed as of 6022b4352e291e299e85b5c60d3d94983296e723
