### ISSUE TITLE
NET PLAY

### ISSUE THREAD

**Issue by hotstyle** [SourMesen/Mesen-S#97]
hello all right friend and about the problem caused in NETPLAY when the person connects to the server has a delay in the second control you can solve this problem because most people play online so if you can solve this problem of delay in PLAYER 2 thank you for the sync this perfect just the delay for the person who enters and that's what is giving problem

**Comment by SourMesen** [comment]
Unfortunately, the way netplay works currently is fairly primitive and does not really work well unless the ping between both players is relatively low.  You probably had a fairly high ping with whoever you were trying to play with, which is causing a fairly large amount of input lag for the other player.

I might one day revisit the way netplay works (on both Mesen & Mesen-S) to improve the latency, etc., but this is not really a priority right now.

**Comment by hotstyle** [comment]
> Infelizmente, a forma como o netplay funciona atualmente é bastante primitiva e não funciona bem a menos que o ping entre ambos os jogadores seja relativamente baixo. Você provavelmente teve um ping bastante alto com quem você estava tentando jogar, o que está causando uma quantidade bastante grande de defasagem de entrada para o outro jogador.
> 
> Eu poderia um dia revisitar a forma como o netplay funciona (tanto em Mesen & Mesen-S) para melhorar a latência, etc., mas isso não é realmente uma prioridade agora.

**Comment by hotstyle** [comment]
> > Infelizmente, a forma como o netplay funciona atualmente é bastante primitiva e não funciona bem a menos que o ping entre ambos os jogadores que estão relativamente baixo. Você provavelmente teve um ping bastante alto com quem você estava tentando jogar, o que está causando uma quantidade grande de defasagem de entrada para o outro jogador.
> > Eu poderia um dia revisitar a forma como o netplay funciona (tanto em Mesen & Mesen-S) para melhorar a latência, etc., mas isso não é realmente uma prioridade agora.

if you could review this emulator on NETPLAY it would be very good most people play a lot online
