### ISSUE TITLE
perfect

### ISSUE THREAD

**Issue by hotstyle** [SourMesen/Mesen-S#99]
the emulator is already perfect tries to improve the NETPLAY for us only that is missing to be a very TOP emulator

**Comment by SourMesen** [comment]
Like I said in the other issue you opened about netplay, I realize there are limitations to the current netplay system, and that it doesn't work in all scenarios.

If you need better netplay, you might want to try retroarch with the mesen-s core (or any other SNES core)

Like I said, I do not have any immediate plans to do additional work on the netplay implementation - there are other things that I would rather focus on (e.g fixing the handful of games that still have issues, etc.)
